name: event-trigger-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(context);
            console.log("==========================================================================================")
            console.log(context.payload);
            console.log("==========================================================================================")

      - name: Create variables
        id: create_variables
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            if (context.event_name === "push") {
              core.setOutput("selector_expression", "some value for push")
            } else {
              core.setOutput("selector_expression", "generic value")
            }
            core.setOutput("test", false)

      - name: step A
        if: ${{ steps.create_variables.outputs.test == 'false' }}
        run: |
          echo Hello there!

      - name: step B
        if: |
          ${{ steps.create_variables.outputs.test == 'false' }}
        run: |
          echo Hello there!
