name: misc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(context);
            console.log("==========================================================================================")
            console.log(context.payload);
            console.log("==========================================================================================")

      - name: env vars
        env:
          TEST_VAR:
        run: |
          printenv | sort
          
      - name: ls /usr/lib
        env:
          TEST_VAR:
        run: |
          ls -al /usr/lib

      - name: ls /usr
        env:
          TEST_VAR:
        run: |
          ls -al /usr
