name: misc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(context);
            console.log("==========================================================================================")
            console.log(context.payload);
            console.log("==========================================================================================")

      - name: env vars
        run: |
          printenv | sort
          
      - name: ls /usr/lib
        run: |
          ls -al /usr/lib

      - name: ls /usr
        run: |
          ls -al /usr

      - name: ls /usr/local
        run: |
          ls -al /usr/local

      - name: npm config list
        run: |
          npm config list

      - name: npm config list -l
        run: |
          npm config list -l

      - name: npm install devcontainers/cli
        run: |
          npm install -g @devcontainers/cli@0

      - name: which devcontaienr
        run: |
          which devcontainer

      - name: ls /usr/local/bin
        run: |
          ls -al /usr/local/bin
