name: test-dispatch

on:
  workflow_dispatch:
    inputs:
      test1:
        description: value for test1
        required: false
        default: DefaultTest1Value
        type: string

jobs:
  run_test:
    name: Run deploy via workflow_call
    uses: ./.github/workflows/fake-extended-3.yml
    with:
      test1: ${{ github.event.inputs.test1 }}
      # test1: ${{ needs.prep_run_test.outputs.anotherSecret }}
      # test1: ${{ secrets.ANOTHER_SECRET }}
      # prRef: ${{ needs.pr_commented.outputs.potentialMergeCommit }}
      # # prRef: ${{ needs.pr_commented.outputs.prRef }}
      # # prRepo: ${{ needs.pr_commented.outputs.prRepo }}
    secrets:
      test2: ${{ secrets.ANOTHER_SECRET }}
      SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}